### ISSUE TITLE
Add keyboard events to move between cells inside the crossword puzzle

### ISSUE THREAD

**Issue by m0nt4ld0** [m0nt4ld0/crucigrama#11]
### Problem
Keyboard events are not configured so you need to click on the table cell to focus on it.

### Why is it important?
Users experience is not good when completing the crossword puzzle.

### 🎯 Possible solution
- Use javascript to capture keyboard events
- Make focus on next cell to the right when the user completes current cell
- Move to next cell to the right when the user press right arrow. If that was the last cell, switch to the next word.
- Move to previous cell (to the left) when the user press left arrow. If that was the first cell, switch to the previous word.

**Comment by 13archae** [comment]
I would like to work this issue.

**Comment by m0nt4ld0** [comment]
@13archae it's assigned to you. Thanks for your collab
