### ISSUE TITLE
Customize your crosswords puzzle - Add customization options - Change colors palette

### ISSUE THREAD

**Issue by m0nt4ld0** [m0nt4ld0/crucigrama#8]
### Problem
Crosswords puzzle doesn't allow users to change the colors palette.

### Why is it important?
It would bring the user the possibility to customize their experience.

### 🎯 Possible solution
All colors are describe in CSS variables with names from a to h. A way to do this would be changing the hex values of this variables. Include a "_Configuration_" section and a form to bring the user the possibility to change the hex values of those variables. Another possibility is to include some predefined palettes (some examples can be taken from https://coolors.co/palette/fffcf2-ccc5b9-403d39-252422-eb5e28)

**Comment by AlonsoSanMar** [comment]
Hi @m0nt4ld0 , I would like to work this issue :), Thank you.
