### ISSUE TITLE
Add progress bar at the bottom of the crossword

### ISSUE THREAD

**Issue by m0nt4ld0** [m0nt4ld0/crucigrama#9]
### Problem
Users can't track their progress when they're playing the game.

### Why is it important?
It enhances UX by showing explicitly their progress in the game.

### 🎯 Possible solution
Include a progress bar [like this](https://getbootstrap.com/docs/5.3/components/progress/#bar-sizing) at the bottom of the current crossword. It fills when the user has completed all the words.

**Comment by paramKeswani** [comment]
hey @m0nt4ld0  can you assign this task to me

**Comment by paramKeswani** [comment]
I have added  progress bar it looks something like this 
![Screenshot 2024-08-21 123523](https://github.com/user-attachments/assets/03464406-2a12-4e72-bb90-fa2fc27e235c)
